image: gcc

build:
  stage: build

  before_script: 
    - apt update
    - apt -y install make autoconf automake libtool pkg-config
    - apt -y install libboost-all-dev
    - apt -y install mdds
  script: 
    - ./autogen.sh --disable-spreadsheet-model && make

test:
  stage: test
  script:
    - make check
