image: gcc

build:
  stage: build
  variables:
    CPPFLAGS: "-D_GLIBCXX_USE_CXX11_ABI=0"
  before_script: 
    - apt update
    - apt -y install make autoconf automake libtool pkg-config
    - apt -y install libboost-all-dev
    - apt -y install libmdds-dev
  script: 
    - ./autogen.sh --disable-spreadsheet-model && make

test:
  stage: test
  script:
    - make check
